### ISSUE TITLE
displayColorDepth raises NumberFormatException when it encounters "4294967296"

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#10]
Several devices in the DeviceDataSource.xml file have the value "4294967296" for displayColorDepth.

This causes OpenDDR to choke when handling displayColorDepth as an integer:

```
Evidence e = new ODDRHTTPEvidence();
e.put("User-Agent", "LG/KF755");
PropertyRef colorDepthRef = identificationService.newPropertyRef("displayColorDepth");
PropertyRef[] propertyRefs = new PropertyRef[] { colorDepthRef };
PropertyValues propertyValues = identificationService.getPropertyValues(e, propertyRefs);
PropertyValue colorDepth = propertyValues.getValue(colorDepthRef);
out.print(colorDepth.getInteger());
```

Changing the last line to this doesn't work either as it raises "ValueException: Not xs:long value":

```
out.print(colorDepth.getLong());
```

Changing the datatype for displayColorDepth in oddrVocabulary.xml does help, however it requires calling code to be changed to use `getLong()` for this property:

```
<Property name="displayColorDepth" datatype="xs:long" aspects="device" defaultAspect="device"/>
```

**Comment by OpenDDR** [comment]
Hi shabbyrobe,
you are right, for some devices the "displayColorDepth" value can not be represented by an Integer value.
The solution to this issue is, as you suggested, to use a Long rather than an Integer.
We have analyzed the getLong() implemetation in PropertyValue Class and we found the follow check:

if (type.equals(TYPE_LONG) || type.equals(TYPE_INT)).

The "displayColorDepth" property is defined, in OpenDDR's vocabularies, as NotNegativeInteger, so we need to extend the check in order to handle also this datatype. In this way the check become:

if (type.equals(TYPE_LONG) || type.equals(TYPE_INT) || type.equals(TYPE_NON_NEGATIVE_INTEGER)).

We have tested this fix and it seems to work fine. We will execute further tests on it. The next release will contains this fix.
Thank you for your support!
Cheers,
OpenDDR Dev. Team

**Comment by shabbyrobe** [comment]
If the vocabulary continues to suggest that the type is an `xs:nonNegativeInteger` though, that would suggest that `PropertyValue.getInteger()` can be used to reliably access the value, which is not the case as long as there are values in the dataset that are greater than `Integer.INT_MAX`.

I think it's clearer to change the type in the vocabulary to an `xs:long`, or even add a non-negative long if the constraint is appropriate, rather than changing `PropertyValue.getLong()` to support an `xs:nonNegativeInteger`. This would encourage users to use the `PropertyValue.getLong()` method to avoid problems as it's immediately clear just from looking at the vocabulary that there will be values that are only capable of being represented as a `long` in Java. 

I do appreciate that this may break people's implementation if they are relying on `getInteger()`, but I think it's clearer.

**Comment by OpenDDR** [comment]
Hi shabbyrobe,
you are right, but we want to avoid changes in Core Vocabulary's W3C specs.

You can find Display Color Depth specs here http://www.w3.org/TR/ddr-core-vocabulary/#sec-displayColorDepth

With our proposed fix we are able to retrieve nonNegativeInteger values above the maximum value of an integer, working around this issue.

Cheers,
OpenDDR Dev. Team

**Comment by shabbyrobe** [comment]
Ahh, I wasn't aware that the vocabulary itself came from the W3C specs too. I'll bookmark those and refer to them in future. Thanks for letting me know!

**Comment by aner-perez** [comment]
Why would you need such a large value for color depth?  It should be the number of _bits_ used for color definition so a display that can render 4294967296 colors should have a color depth of "32".  Sounds like the field is being used incorrectly.

**Comment by shabbyrobe** [comment]
I never even thought of it that way, but it's exactly as you say. From the W3 docs:

> 4.6.4 Measurement
> 
> Count the number of bits used for color definition.
> 
> 4.6.6 Note
> 
> If you are making any image or video transcoding it is important to know the maximum colors addressable by the screen. Measuring in bits should make it easier for programmatic conversions.
