### ISSUE TITLE
Missing Pattern.quote() in AndroidDeviceBuilder

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#11]
I know this is an unlikely one to ever trip, but it seems that a couple of enterprising folks managed to fire us off some user agents that tripped it. Any Android user agent that has a regex metacharacter inside the portion matched by `AndroidDeviceBuilder.buildHashPattern` will raise a `java.util.regex.PatternSyntaxException`.

This is one of the specific agents we saw that tripped it:

```
Mozilla/5.0 (Linux; U; Android; LG-P350 Build/{BUILD}) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1 MMS/LG-Android-MMS-V1.0/1.2
```

It's not a severe problem by any stretch, but it's fixed simply by changing line 230 of `AndroidDeviceBuilder` from

```
patternElementInsideClean = patternElementInsideClean.replaceAll("Build/" + build, "Build/");
```

To:

```
patternElementInsideClean = patternElementInsideClean.replaceAll("Build/" + Pattern.quote(build), "Build/");
```

**Comment by msponer** [comment]
Cool, thank you -- I also saw this problem in our logs but had not patched it. I used your patch, and would do a pull request to add it here except that our forks are out of sync at the moment. Thanks again.

**Comment by shabbyrobe** [comment]
Oh, my bad. I'll get my fork in order today.

**Comment by msponer** [comment]
Oh, I meant my fork, not yours or OpenDDRdotORGs.

I added a pull request (Issue 12) that includes this fix, but it's a little messy since it includes other patches I've made. If that won't work for folks we can do this as a separate patch.
