### ISSUE TITLE
NokiaN9\d fail to match - return N9-00 instead

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#13]
Not sure if this belongs here or in the resources repo. It can be fixed just by tweaking the XML, but it could also be fixed by tweaking TwoStepDeviceBuilder.

The following agents (and many similar ones that contain `NokiaN\d\d`) don't match the appropriate devices, instead they match an N9-00:

```
NokiaN90-1/3.0535.4.3/SN356633000142768 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1
NokiaN91-2/3.0 (3.10.023) SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
NokiaN93/20.0.058 SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
NokiaN95/1.0 (11.1.010) SymbianOS/9.2 Series60/3.1 Profile/MIDP-2.0 Configuration/CLDC-1.1
```

This can be fixed by changing the BuilderDataSource.xml file to use capitals in the second value for all of the `Nokia N9\d` agents under the two step builder:

```
<device id="Nokia N91">
  <list>
    <value>Nokia</value>
    <value>N91</value>
  </list>
</device>
```

When I run `[Nn]okia\s?n9\d` over our agent logs, I get no instance of anything that shows a lowercase `N` before the numbers.

Actually, it appears that it does match the devices properly, but with a 60% confidence that is below my 70% threshold setting. I think the two step builder might also be penalising the devices a bit too harshly in this case - it cops a -20% for not being a case sensitive match, and a further -20% due to there being no distance between the tokens.

**Comment by shabbyrobe** [comment]
Woops, I did end up meaning to post this on the resources repo in the end.

**Comment by OpenDDR** [comment]
Hi shabbyrobe!
We have analyzed your issue; we think the better place to address this bug is the TwoStepDeviceBuilder.
In fact, analyzing the code of the TwoStepDeviceBuilder, we found a bug when the if istruction "betweenTokensLength <= 1" is satisfied. The regexp "._[ _/-]._" should be "[ _/-]?" in order to allow "betweenTokens" of zero length.
As soon as we will complete the "no regression tests", we will commit the fix!
Thank you for your support!
Cheers,
OpenDDR Dev. Team

**Comment by shabbyrobe** [comment]
I've done some testing on this by running about half a million agents from our logs against an unfixed version, then against a version with the TwoStepDeviceBuilder fix proposed and a version with the XML file changes in the original post.

The regex change improves the N9x matching, but it also introduces a few regressions. Updating the XML as I suggested improves the N9x matching equally well, but introduces no regressions.

I can't believe I've never noticed there's no way to attach files to Github issues. What's the best way to send you a small CSV file of the regressions I have found?

**Comment by shabbyrobe** [comment]
Actually, the XML fix does introduce one device that matches incorrectly, but I'm not sure it can be considered a regression because it was wrong before the fix too. Nokia N900 - previously matched N9-00, matches N90 after applying the XML fix. Though this actually appears to be due to a missing entry in BuilderDataSource.xml for the N900. Adding this to the Builder file under the TwoStepDeviceBuilder fixes the N900:

```
        <device id="N900">
          <list>
            <value>Nokia</value>
            <value>N900</value>
          </list>
        </device>
```

**Comment by shabbyrobe** [comment]
I've investigated the N900 thing further - turns out there is a builder entry for it already, but it expects RX-51 in the agent. Most of the N900-esque agent strings in my logs match just fine as they contain the RX-51 element. The N900 agents I mentioned in my previous message are either truncated and possibly erroneous, or otherwise they look a bit strange:

```
YahooMobileMessenger/1.0 (Android Mail; 1.3.6) (n900; unknown; Nokia N900; 2.3.4/GRJ22)
YahooMobileMessenger/1.0 (Android Messenger; 1.5.0) (n900; unknown; Nokia N900 Community Indonesia; 3.2.1/GRJ22)
```

So I guess it's not an issue and you can disregard my previous message about N900s.

**Comment by OpenDDR** [comment]
Hi shabbyrobe!
You can send your csv file to info@openddr.org. We are happy to analyze it.
Cheers,
OpenDDR Dev. Team
