### ISSUE TITLE
Nokia user agents containing an SN1236340999 portion confusing TwoStepDeviceBuilder

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#14]
The following user agent matches the Nokia6340 device instead of the Nokia N90:

```
NokiaN90-1/3.0535.4.3/SN356634001839154 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1
```

The reason for this is that the `6340` token appears inside the `SN......` segment. According to my logs, this actually happens quite a bit. 

Here are some other examples: 
`NokiaN72/5.0819.4.0.1/SN355721021257797 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1` returns a Nokia 2125 instead of an N72
`NokiaN70//SN359570017923201 5.0741.4.0.1 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1` returns a Nokia3595 instead of an N70...

I think this is pretty similar to the issue I described in issue #13. I'm reluctant to proffer a solution given I'm still not yet familiar enough with the best place to make fixes like this.

**Comment by OpenDDR** [comment]
Hi shabbyrobe!
Thank you for your report! You are right, often it's possible to find numeric token inside the SN segment. We are handling this issue.
You can find the fix in the next release.
Thank you!
OpenDDR Dev. Team
