### ISSUE TITLE
Opera user agent "Presto" portion causes device identificator to return Palm Pre

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#15]
Again, not sure which project is best for this as I think this issue also relates to the same TwoStepDeviceBuilder problems as my other issues from today, but I'm not fully sure yet.

Opera user agents contain a "Presto" version, which according to [this blog post](http://my.opera.com/core/blog/presto-in-the-the-opera-user-agent-string) relates to the version of the Opera core.

OpenDDR matches the Opera browser correctly, but the device identificator incorrectly determines that the Presto/2.1.1 bit corresponds to a Palm Pre.

For example, the agent `Opera/9.62 (Windows NT 6.0; U; en) Presto/2.1.1` returns the `Pre/1.1` device.

**Comment by OpenDDR** [comment]
Hi shabbyrobe!
The best way to solve this issue is by modifying the "BuilderDataSource.xml"; in particular, we should modify the entry for "Pre/1.1" in the TwoStepDeviceBuilder section. We are working on the fix, we think it will be available for next release!
Thank you!
OpenDDR Dev. Team
