### ISSUE TITLE
Add dClass as a C API for OpenDDR?

### ISSUE THREAD

**Issue by huayra** [OpenDDRdotORG/OpenDDR-Java#19]
dClass - Device Classification Engine works great with nginx and Varnish and is using OpenDDR as its DDR. Maybe you should consider adding the library to your releases? You are lacking a C API and dClass would certainly cover that user need and more: https://github.com/TheWeatherChannel/dClass

**Comment by tiwilliam** [comment]
:+1:

**Comment by OpenDDR** [comment]
Considering this, created a question in the C# client repo
