### ISSUE TITLE
oddr.ua.device.builder.patch.paths has to contain ','

### ISSUE THREAD

**Issue by gounthar** [OpenDDRdotORG/OpenDDR-Java#21]
Hi,

the two properties oddr.ua.device.builder.patch.paths and oddr.ua.device.datasource.patch.paths must contain a ',' character, because you use the "split" method on the values.
If the value doesn't contain any ',' (i.e. just one file path), the patch is just ignored.

**Comment by OpenDDR** [comment]
Hi gounthar,
Thank you for your contribute. As you said in issue #22, 'oddrUaDeviceBuilderPatchStreams' and 'oddrUaDeviceDatasourcePatchStreams' were always not null, so 'oddrUaDeviceBuilderPatchPaths' and 'oddrUaDeviceDatasourcePatchPaths' were always ignored. 
We have fixed this issue as you suggest.

Cheers,
OpenDDR Dev. Team
