### ISSUE TITLE
Are some properties "filtered"?

### ISSUE THREAD

**Issue by gounthar** [OpenDDRdotORG/OpenDDR-Java#23]
Hi,

I'm currently using OpenDDR to identify a SonyEricsson Z1010.
I used the getPropertyValues().getAll() method of the Servce class, but some properties are missing (I'm looking for the "columns" property):

``` java
PropertyRef[] propertyRefs = new PropertyRef[] { displayWidthRef,
displayHeightRef, vendorRef, modelRef, idRef };
Evidence e = new ODDRHTTPEvidence();
e.put("User-Agent", userAgent);
PropertyValue[] values = identificationService.getPropertyValues(e) .getAll();
```

Here are the properties that exist and their value:
ajax_manipulate_css/false
ajax_manipulate_dom/false
ajax_support_event_listener/false
ajax_support_events/false
ajax_support_getelementbyid/false
ajax_support_inner_html/false
ajax_support_javascript/false
displayHeight/220
displayWidth/176
dual_orientation/false
id/SonyEricssonZ1010
image_inlining/false
is_tablet/false
is_wireless_device/true
model/Z1010
nokia_edition/0
nokia_series/0
vendor/SonyEricsson
xhtml_format_as_attribute/false
xhtml_format_as_css_property/true

In the DeviceDataSource.xml, I can see:

``` xml
    <device id="SonyEricssonZ1010" parentId="genericSonyEricsson">
      <property name="receiver" value="true" />
      <property name="mms_max_size" value="261120" />
      <property name="columns" value="15" />
```

I suppose I missed something. Why don't I get all the properties?

Best regards.

**Comment by OpenDDR** [comment]
Hi gounthar,
you should open your oddr.properties file and check if the property oddr.limited.vocabulary.path is setted.
This property is used to define a reduced vocabulary (oddrLimitedVocabulary.xml) that contains only the needed properties.
In this way, only the properties needed by the user are loaded in memory.
Maybe the 'columns' property is not in your oddrLimitedVocabulary.xml. If you need all the available properties in OpenDDR vocabulary, you should remove the oddr.limited.vocabulary.path property in your oddr.properties.
Cheers,
OpenDDR Dev. Team.

**Comment by gounthar** [comment]
Hi OpenDDR Dev. Team,

you were right about the oddrLimitedVocabulary.xml file. I removed the oddr.limited.vocabulary.path property, and the columns property automagically appeared.
If you write a FAQ, that question could possibly figure in it.

Thanks!
