### ISSUE TITLE
Identify BlackBerry 10 browser

### ISSUE THREAD

**Issue by hsteve** [OpenDDRdotORG/OpenDDR-Java#26]
Currently OpenDDR does not identify devices that are using the BlackBerry 10 browser. 

According to RIM (http://devblog.blackberry.com/2012/08/blackberry-10-user-agent-string/) and supported by some testing I have just carried out, BlackBerry 10s have user agents of the form:

`Mozilla/5.0 (BB10; <Device Model>) AppleWebKit/<WebKit Version> (KHTML, like Gecko) Version/<BB Version #> Mobile Safari/<WebKit Version>`

e.g.

`Mozilla/5.0 (BB10; Touch) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.0.10.648 Mobile Safari/537.10+`

A fairly simple change to BlackBerryBrowserBuilder.java looks to be all that is needed. Would it be helpful if I submitted this change?

**Comment by OpenDDR** [comment]
Moved to openddr-data
