### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by acmeguy** [OpenDDRdotORG/OpenDDR-Java#33]
Hi,

http://www.openddr.org/download/OpenDDR-Java-1.0.0.27.zip results in this:
http://www.openddr.org/cgi-sys/suspendedpage.cgi and some ads.

Regards,
  -Stefan

**Comment by keilw** [comment]
Thanks for pointing this out. Note active development was contributed to Apache DeviceMap, see http://incubator.apache.org/devicemap/index.html

The DeviceMap project is currently in the process of graduation review. As soon as it graduates from the incubator, you'll find downloads of the Java API(s) as well as device data under Apache.org. In the meantime check SVN snapshots of both.

Regards,
Werner

**Comment by OpenDDR** [comment]
Old site, no longer relevant
