### ISSUE TITLE
OpenDDR vocabulary file contains mixture of datatype and dataType attributes

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#7]
When I use some of the older property names, the PropertyValue class get...() methods throw NullPointerExceptions as `type` is set to null.

This appears to be because the `oddrVocabulary.xml` file contains both `datatype` and `dataType` casing for the type attribute, although the `VocabularyHandler` class only uses `datatype`:

```
public class VocabularyHandler extends DefaultHandler {

    private static final String ATTRIBUTE_PROPERTY_DATA_TYPE = "datatype";
```

I fixed the xml files by doing a quick sed:

```
sed -i "" 's/dataType/datatype/g' oddrVocabulary.xml
```

**Comment by OpenDDR** [comment]
Hi shabbyrobe,
you are perfectly right!
As you say there is a mix of "datatype" and "dataType" in oddrVocabulary.xml and if you try to access some properties by a getter method, different from getString(), we have an exception. We will fix the oddrVocabulary.xml in the next release (planned for next week). 

Best regards,
OpenDDR Dev. Team
