### ISSUE TITLE
Opera Mini on iPhone not detected

### ISSUE THREAD

**Issue by shabbyrobe** [OpenDDRdotORG/OpenDDR-Java#9]
Opera mini for iPhone user agents (for e.g. `Opera/9.80 (iPhone; Opera Mini/5.0.0176/18.674; U; en) Presto/2.4.15`) always return "Mobile Safari 1.0.0.0" as the browser.

This is solved by moving `OperaMiniBrowserBuilder` up above `SafariMobileBrowserBuilder` in `DefaultBrowserBuilder.java`.

**Comment by OpenDDR** [comment]
Dear shabbyrobe,
thank you for your suggestion!
You are right, by moving OperaMiniBrowserBuilder up above SafariMobileBrowserBuilder in DefaultBrowserBuilder.java, OpenDDR correctly identifies Opera Mini browser for iPhone User-Agent.
We are running some no-regression tests before modify the sorting in DefaultBrowserBuilder.java.
We will release this fix in the next release (planned for first week of May).

Cheers,
OpenDDR Dev. Team

**Comment by shabbyrobe** [comment]
Great! Thanks for getting back to me so quickly. FWIW, in my own tests against 50k of the user agents we see here, I recorded an overall uptick in match quality.
